### ISSUE TITLE
Missing edges in pathways 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#771] opened 2018-05-18 20:07 UTC
## Environment info

- Browser version (client) : Chrome (Version 66.0.3359.181 (Official Build) (64-bit)) / Firefox (59.0.2 (64-bit))
- Node.js version (server) : 8

## Current (buggy) behaviour

Missing edges in pathways.

## Desired behaviour

Should have edges.

## Minimum steps to reproduce

Desired [Transcriptional activation of cell cycle inhibitor p21 | Reactome](http://apps.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895)

![screenshot at may 18 16-02-25](https://user-images.githubusercontent.com/4706307/40255515-673428c4-5ab5-11e8-8f8d-9efe47d7e112.png)

Development [Transcriptional activation of cell cycle inhibitor p21 | Reactome
![screenshot at may 18 16-02-15](https://user-images.githubusercontent.com/4706307/40255524-761878ae-5ab5-11e8-9175-7d50286648c1.png)
](http://appsbeta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895)

**Comment by IgorRodchenkov** [comment] 2018-05-24 19:56
Let's fix (we need this new app for PC10 testing and release now)

**Comment by maxkfranz** [comment] 2018-05-28 15:14
Have we identified whether this is a data issue or a UI issue?  

If it's a UI issue, it could be a problem with using cytoscape#unstable.  If so, it may make sense to use only official releases.  That may mean some refactoring re. `cy.mount()`.

**Comment by IgorRodchenkov** [comment] 2018-05-28 16:02
It's probably not a pathway data issue (PC data, services are same; I tried with PC10 beta URL - same issues)

**Comment by d2fong** [comment] 2018-05-30 15:24
It doesn't happen in the master branch so it is possible that there is some commit in development that broke it.

**Comment by d2fong** [comment] 2018-05-30 15:39
Warnings are from this commit
https://github.com/cytoscape/cytoscape.js/commit/b74f9efee5ad629772383a3a05bc9a194618bf90

But I don't think we use bezier edges for the sbgn stylesheet

**Comment by d2fong** [comment] 2018-05-30 15:41
Actually we do

https://github.com/PathwayCommons/cytoscape-sbgn-stylesheet/blob/9eaeb2377a6e37cd2c734c4bf4ca7a9f79110f3d/src/sbgnStyle/index.js

But I don't know why we need to. Most arrows are just straight.

**Comment by d2fong** [comment] 2018-05-30 15:41
Maybe we just need to update the stylesheet.

**Comment by d2fong** [comment] 2018-05-30 15:51
When I set ```'curve-style': 'haystack'```
The warnings disappear but it looks like this:

![screen shot 2018-05-30 at 11 50 16 am](https://user-images.githubusercontent.com/2328291/40731730-aa20f376-63ff-11e8-9fc8-a0e72308066d.png)

**Comment by d2fong** [comment] 2018-05-30 15:52
When I set ```'haystack-radius': 1``` it looks like this. 
![screen shot 2018-05-30 at 11 52 03 am](https://user-images.githubusercontent.com/2328291/40731829-e8edb9cc-63ff-11e8-807e-23b4bb03ca7d.png)

**Comment by d2fong** [comment] 2018-05-30 16:00
If you set it to curve-style segments, you get this interesting effect:

![screen shot 2018-05-30 at 11 59 26 am](https://user-images.githubusercontent.com/2328291/40732292-fe39394a-6400-11e8-9a11-58ee5126c036.png)

**Comment by maxkfranz** [comment] 2018-05-30 16:01
The problem is with the `intersectLine()` of `cut-rectangle`.  This has not changed in cytoscape.js, so something has must have changed in app-ui or the sbgn-stylesheet that causes the cut-rectangle intersection to fail.

**Comment by d2fong** [comment] 2018-05-30 16:04
Maybe it was always broken, but since logging was added we are now discovering that it was broken?  sbgn-stylesheet hasn't been touched in 6 months and that was only for the new tooling work we did (webpack build stuff).

**Comment by maxkfranz** [comment] 2018-05-30 16:30
It has to do with import/export changes and babel/webpack.  If you `npm i && npm run watch` now, I think it should work.

I'm still seeing warnings in the console, so there are some other cases where app-ui is creating invalid edges.  Is there some kind of animation going on during initial load?  If so, that should be turned off.

N.b. the next time we merge to master, we should lock down the version of cytoscape#unstable used with a commit hash.

**Comment by d2fong** [comment] 2018-05-30 16:33
Why does it only work if you do npm i && npm run watch?

**Comment by maxkfranz** [comment] 2018-05-30 16:38
The cytoscape#unstable code now uses import/export instead of require/module.  Depending on how faithfully babel transforms the `pointInsidePolygon()` function, `arguments` may or may not work.

**Comment by maxkfranz** [comment] 2018-06-04 16:33
Closing as this should be OK now

**Closed by maxkfranz** 2018-06-04 16:33 UTC
Labels: 1 high priority, bug, search module
